### ISSUE TITLE
TypeError: ml.classifiers.detail is not a function

### ISSUE THREAD

**Issue by KyleAMathews** [monkeylearn/monkeylearn-node#1]
Installed this and tried to get details about a classifier and got this error.

**Comment by rsteca** [comment]
It's working fine for me. I used:



    var MonkeyLearn = require('monkeylearn');
     
    var ml = new MonkeyLearn('<Your token here>');
    var module_id = '<the module id>';
    var p = ml.classifiers.detail(module_id);
    p.then(function (res) {
        console.log(res.result);
    });

Can you paste the code you are using?

**Comment by KyleAMathews** [comment]
I pasted your exact code into a test.js file and ran it and got the same error.

Running node v4.2.1 and monkeylearn v0.1.2

**Comment by rsteca** [comment]
Upgrading to node v5.0.0 should solve the problem. But I will check out why it's not working on v4.2.1. Thanks for reporting!

**Comment by rsteca** [comment]
Fixed on #2
